pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Backmerge from master when the author is trusted 
    actions:   
      backport:      
        regexes:      
        - (^develop$)|(^hotfix\/(.+)$)|(^release\/(.+)$) 
    conditions:
    - closed 
    - merged 
    - author~=(^danielrayar$)|(^dependabot.*$)|(^mergify.*$) 
    - base=master
  - name: Backmerge from release1.0.1 when the author is trusted 
    actions:   
      backport:      
        regexes:      
        - (^develop$)|(^release\/(.+)$) 
    conditions:
    - closed 
    - merged 
    - author~=(^danielrayar$)|(^dependabot.*$)|(^mergify.*$) 
    - base=release/1.0.1   